# serverless.yml

service: circleci-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
 - serverless-offline