# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and Protractor
          command: |
            sudo npm i -g serverless
            sudo npm i -g protractor
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Setup Selenium binaries
          command: sudo webdriver-manager update

      - run:
          name: Start Selenium
          command: sudo webdriver-manager start
            background: true

      - run:
          name: Start Serverless in offline mode
          command: serverless offline start
            background: true

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Deploy application
          command: sls deploy

